# Generated by Django 5.0.4 on 2024-04-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('name', models.CharField(max_length=80)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.BooleanField(verbose_name=False)),
            ],
        ),
    ]
